# 该文件用来在 github actions 中自动运行脚本
name: Send messages regularly

on:
  schedule:
  # 定时运行的时间，国际标准时间，北京时间要+8
  - cron:  '59 23 * * *'
  workflow_dispatch: 
 
jobs:
  run-coupons: 
    name: GoodMorning # 任务名
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main  #采用main分支下的
           
      - name: Setup Node.js
        uses: actions/setup-node@v2  #安装node.js
        with:
          node-version: '16'
          
      - name: Install Dependency       
        run: |
          npm install xmlhttprequest     
          node ./index.js  # 要运行的js脚本，放在根目录下
          
        # 读取Actions secrets保存的信息
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
          CITY: ${{ secrets.CITY }}
          START_DATE: ${{ secrets.START_DATE }}
          BIRTHDAY1: ${{ secrets.BIRTHDAY1 }}
          BIRTHDAY2: ${{ secrets.BIRTHDAY2 }}
          USER_ID: ${{ secrets.USER_ID }}
          TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
